---
abstract: 'process template files in your dist using Template::Tiny'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::DZil: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Template-Tiny
no_index:
  directory:
    - corpus
requires:
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::FileInjector: 0
  Dist::Zilla::Role::FileMunger: 0
  Dist::Zilla::Role::FilePruner: 0
  List::Util: 0
  Moose: 0
  Template::Tiny: 0
  namespace::autoclean: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/Dist-Zilla-Plugin-Template-Tiny/issues
  repository: git://github.com/plicease/Dist-Zilla-Plugin-Template-Tiny.git
version: 0.01
